# Generated by Django 4.2.1 on 2023-05-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAutor', models.CharField(help_text='Ingrese el nombre del autor', max_length=100)),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloLibro', models.CharField(help_text='Ingrese el titulo del libro', max_length=100)),
                ('numeroPaginaLibro', models.CharField(help_text='Ingrese el numero de pagina del libro', max_length=100)),
                ('editorialLibro', models.CharField(help_text='Ingrese la editorial del libro', max_length=100)),
                ('isbnLibro', models.CharField(help_text='Ingrese el isbn del libro', max_length=150)),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPublicacion', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor', verbose_name='autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro', verbose_name='libro')),
            ],
            options={
                'verbose_name': 'publicacion',
                'verbose_name_plural': 'publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacionEjemplar', models.CharField(help_text='Ingrese la localizacion', max_length=150)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro', verbose_name='libro')),
            ],
            options={
                'verbose_name': 'ejemplar',
                'verbose_name_plural': 'Ejemplares',
            },
        ),
    ]
