# Generated by Django 4.2.1 on 2023-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='libro',
            field=models.ManyToManyField(through='biblioteca.Publicacion', to='biblioteca.libro', verbose_name='publicacion'),
        ),
    ]
