# Generated by Django 4.2.1 on 2023-05-17 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDevPrestar', models.DateField()),
                ('fechaPresPrestar', models.DateField()),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.ejemplar', verbose_name='ejemplar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'prestar',
                'verbose_name_plural': 'prestamos',
            },
        ),
    ]
