# Generated by Django 4.2.1 on 2023-05-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(help_text='Ingrese el nombre del usuario', max_length=100)),
                ('apellidosUsuario', models.CharField(help_text='Ingrese los apellidos del usuario', max_length=100)),
                ('direccionUsuario', models.CharField(help_text='Ingrese la direccion del usuario', max_length=100)),
                ('telefonoUsuario', models.CharField(help_text='Ingrese el Telefono del usuario', max_length=12)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
